### ISSUE TITLE
Is there anyway by which I can pass my own distance matrix ? 

### ISSUE THREAD

**Issue by somnathasati** [tgsmith61591/clust4j#8]

**Comment by tgsmith61591** [comment]
Not currently, since many of the algos do not end up using a pre-computed distance matrix (i.e., neighbors algos use a KDTree or BallTree). Do you have a specific use case?

**Comment by somnathasati** [comment]
Yes, the data i am trying to fit will not give good result using euclidean or any other existing so can i make new GeometricallySeparable object like this(https://ideone.com/AewWKH) having different distance computation and pass it to HDBSCANParameters setMetric() method ?

**Comment by tgsmith61591** [comment]
That's probably the best approach. What metric are you considering?

**Comment by somnathasati** [comment]
it's distance between words bounding boxes by calculating the closest distance of their outlines toward each other.

**Comment by tgsmith61591** [comment]
Do you have a formula?

**Comment by somnathasati** [comment]
Please check !

def rect_distance((x1, y1, x1b, y1b), (x2, y2, x2b, y2b)):
    left = x2b < x1
    right = x1b < x2
    bottom = y2b < y1
    top = y1b < y2
    if top and left:
        return dist((x1, y1b), (x2b, y2))
    elif left and bottom:
        return dist((x1, y1), (x2b, y2b))
    elif bottom and right:
        return dist((x1b, y1), (x2, y2b))
    elif right and top:
        return dist((x1b, y1b), (x2, y2))
    elif left:
        return x1 - x2b
    elif right:
        return x2 - x1b
    elif bottom:
        return y1 - y2b
    elif top:
        return y2 - y1b
    else:             # rectangles intersect
        return 0.

**Comment by somnathasati** [comment]
Please review ! https://ideone.com/8DYpqt. I am going to put in getDistance() function of GeometricallySeparable object instance.

**Comment by tgsmith61591** [comment]
So my only concern here is that the two vectors that your formula computes
against require dims of length 4. This is ok supposing you'll only have 4
features in your matrices.

Taylor G. Smith
T 512.576.8906

**Comment by somnathasati** [comment]
Is there any constraint on the dimensions ?

**Comment by tgsmith61591** [comment]
The formula you presented requires the vectors to be four-long

**Comment by somnathasati** [comment]
Can you please help me with some bug , this (https://ideone.com/qxDBeH) is not working and it's happening for few more data too. the four-long vectors are (x,y , width , height). The null pointer exception is coming from line 1327(https://ideone.com/CRSSju)

**Comment by tgsmith61591** [comment]
The only exceptions I'm seeing in the code you linked are compilation issues and `IllegalStartOfExpression` exceptions. Not seeing any NPEs. Also, I must have missed that this is for HDBSCAN&mdash;the HDBSCAN algo uses a very specific set of distance metrics (IIRC it's `EuclideanDistance`, `ManhattanDistance`, `MinkowskiDistance` and `ChebyshevDistance`).

Taking a closer look at your code (which is Python, btw?) I'm thinking the best approach here is *not* to define your own distance metric, but to find a way to preprocess your data such that rows represent the vertices between objects that you're trying to compute distance between. I still don't quite understand what your objective is here (just compute distance between nearest vertex of objects?) but this is definitely not an algorithmic problem, and is more of a data preparation issue.

Hope this makes sense. Since the issue at hand has been addressed, I'm going to close this out.

**Comment by somnathasati** [comment]
At start, i thought to pre process the data or prepare it only but the problem is: 

"which vertex of the rectangle i have to choose for two rectangles depends upon relative locations" those are not fixed otherwise it would be simple. 

So either i can compute distance matrix by myself which i can not paas as of now. So i thought to put the distance matrix function using the parameter it has. 

But, I am getting exceptions can you please try this(https://ideone.com/qxDBeH) with the 2D array and Distance matrix it has for last time whenever you will be free with your code. Great Thanks !

**Comment by somnathasati** [comment]
Apologies for asking a lot but i am observing one thing the clustering (https://ideone.com/qxDBeH) works if I will include setMinClustSize(14).setMinPts(7). unable to catch how distance matrix or something is affecting the behavior. Can think of anything why it can through exception at 1327 (https://ideone.com/CRSSju)
